### ISSUE TITLE
Too many releases

### ISSUE THREAD

**Issue by schlimmchen** [helgeerbe/OpenDTU-OnBattery#420]
### What happened?

It seems that for every tag that is *merged*, a release is built and published.

### To Reproduce Bug

See releases posted today, 2023-09-04.

### Expected Behavior

Only one release will be built and published once @helgeerbe merges development into master.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

n/a

### Anything else?

Thanks for promptly merging pull requests and releasing firmware for everybody to enjoy, @helgeerbe. However, I find it confusing for people that multiple releases seem to include similar changes. I think that this is not what you intended? Do you want one release per tag on the master branch **after** merging development into master? Currently it seems that also other tags (from other forks?!) cause releases to be built and published...

Also, not that it was important, but the JK BMS serial support is sorted under section "Under the hood". Is there something I need to do so that such a feature is listed in the respective section of the changelog/release info?

**Comment by schlimmchen** [comment]
Nice!

The following releases were created because I created respective tags for them in my fork:
* https://github.com/helgeerbe/OpenDTU-OnBattery/releases/tag/2023.08.30-vedirect-debugging
* https://github.com/helgeerbe/OpenDTU-OnBattery/releases/tag/2023.08.29-jkbms

Why does that happen? Why are those tags even part of this repo? Actually... the same question applies for the tags made in the upstream project. I am confused... Does github automagically create them when merging pull requests? I really don't think that this is a pure GIT feature.

And those two tags from my fork would still trigger releases based on the `startsWith` approach...

**Comment by helgeerbe** [comment]
Tags points to a specific commit. So yes, they are merged. To build actions on them, we have to use patterns which we can filter.

**Comment by helgeerbe** [comment]
@schlimmchen If it is fine for you, I would close this issue. The actual script is not perfect, but it works so so far.

**Comment by schlimmchen** [comment]
what about v23.9.18? wasn't that compiled by accident as well?

to be honest, I don't care too much, I mainly wanted to bring this to your attention.

**Comment by helgeerbe** [comment]
It's build, but not released.

I coud try:

````yaml
  build:
    name: Build Enviornments
    runs-on: ubuntu-latest
    needs: get_default_envs
    strategy:
      matrix:
        environment: ${{ fromJSON(needs.get_default_envs.outputs.environments) }}
    if: !startsWith(github.ref, 'refs/tags/v2')
````

**Comment by helgeerbe** [comment]
Checking the yaml code, I'm wondering why this does not work?

````yaml
on:
  push:
    paths-ignore:
      - docs/**
      - '**/*.md'
    branches:
      - master
      - development
    tags-ignore:        
      - v*
  pull_request:
    paths-ignore:
      - docs/**
      - '**/*.md'
````

**Comment by schlimmchen** [comment]
> It's build, but not released.

https://github.com/helgeerbe/OpenDTU-OnBattery/releases/tag/v23.9.18 :man_shrugging: 

I don't know YAML and I dont know github workflows, but this (already implemented) should do the trick:

```yaml
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [get_default_envs, build]
    if: startsWith(github.ref, 'refs/tags/2')
```

> Checking the yaml code, I'm wondering why this does not work?

I don't know either. I agree that the whole workflow should be skipped entirely for tags that start with a "v". There might be other events than "push" that trigger the workflow, in which case the filter is not working. I don't know...

> I coud try:

Yes, this would be my next try as well. Preventing a build for tags that start with a "v". You forgot double quotes, which are needed due to the exclamation point (as per chatGPT, I don't know any YAML):

```yaml
  build:
    [...]
    if: "!startsWith(github.ref, 'refs/tags/v')"
```
